services:
# database
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    networks:
      - evm-event-indexer-network
    volumes:
      # load schema from local directory for initialization
      - ./db:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

# redis
  redis:
    image: "redis:8.4.0"
    ports:
      - "6379:6379"
    networks:
      - evm-event-indexer-network

# local Ethereum node for testing
  anvil:
    image: ghcr.io/foundry-rs/foundry:stable
    entrypoint: anvil
    command: ["--host", "0.0.0.0", "--port", "8545", "--chain-id", "31337"]
    ports:
      - "8545:8545"
    networks:
      - evm-event-indexer-network

# main service for indexing EVM events
  indexer:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: evm-event-indexer
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
      anvil:
        condition: service_started
    ports:
      - "8080:8080"
    networks:
      - evm-event-indexer-network      
    environment:
      - TZ=UTC # default timezone 
      - WAIT_FOR_START=10s
      - LOG_LEVEL=debug
      # session
      - SESSION_AT_EXPIRATION=15m
      - SESSION_RT_EXPIRATION=1h
      - SESSION_JWT_SECRET=secret
      - SESSION_CSRF_SECRET=secret
      # mysql
      - MYSQL_MAX_OPEN_CONNS=10
      - MYSQL_MAX_IDLE_CONNS=10
      - MYSQL_CONN_MAX_LIFE_TIME=5m
      - MYSQL_RETRY=10
      - MYSQL_WAIT_DURATION=10s
      - MYSQL_TIMEOUT=30s
      # mysql event db
      - MYSQL_DATABASES_EVENT_DBM_NAME=event_db
      - MYSQL_DATABASES_EVENT_DBM_IP=mysql
      - MYSQL_DATABASES_EVENT_DBM_PORT=3306
      - MYSQL_DATABASES_EVENT_DBM_ACCOUNT=root
      - MYSQL_DATABASES_EVENT_DBM_PASSWORD=root
      - MYSQL_DATABASES_EVENT_DBS_NAME=event_db
      - MYSQL_DATABASES_EVENT_DBS_IP=mysql
      - MYSQL_DATABASES_EVENT_DBS_PORT=3306
      - MYSQL_DATABASES_EVENT_DBS_ACCOUNT=root
      - MYSQL_DATABASES_EVENT_DBS_PASSWORD=root
      # mysql account db
      - MYSQL_DATABASES_ACCOUNT_DBM_NAME=account_db
      - MYSQL_DATABASES_ACCOUNT_DBM_IP=mysql
      - MYSQL_DATABASES_ACCOUNT_DBM_PORT=3306
      - MYSQL_DATABASES_ACCOUNT_DBM_ACCOUNT=root
      - MYSQL_DATABASES_ACCOUNT_DBM_PASSWORD=root
      - MYSQL_DATABASES_ACCOUNT_DBS_NAME=account_db
      - MYSQL_DATABASES_ACCOUNT_DBS_IP=mysql
      - MYSQL_DATABASES_ACCOUNT_DBS_PORT=3306
      - MYSQL_DATABASES_ACCOUNT_DBS_ACCOUNT=root
      - MYSQL_DATABASES_ACCOUNT_DBS_PASSWORD=root
      # redis
      - REDIS_RETRY=10
      - REDIS_WAIT_DURATION=1s
      - REDIS_PING_TIMEOUT=500ms
      # redis user db
      - REDIS_DATABASES_USER_IP=redis
      - REDIS_DATABASES_USER_PORT=6379
      - REDIS_DATABASES_USER_DB=1
      # scanner json file path
      - SCANNER_PATH=./config/scanner.docker.json
    volumes:
      - ../config:/app/config:ro
networks:
  evm-event-indexer-network:
    name: indexer-network
    driver: bridge