#
scanner_path: "./config/scanner.json"
wait_for_start: "0s"
decoders: 
  - name: "Transfer"
    signature: "Transfer(address,address,uint256)"
  - name: "Approval"
    signature: "Approval(address,address,uint256)"
log_scanner_interval: "5s"
reorg_window: 10
log_level: "debug"
timeout: "30s"
retry: 10
backoff: "1s"
max_backoff: "30s"
api:
  port: "8080"
  timeout: "30s"
argon2:
  time: 1
  memory: 65536
  threads: 2
  key_len: 32  
session:
  at_expiration: "15m"
  rt_expiration: "1h"
  jwt_secret: "secret" # should be replaced from environment variable
mysql:
  max_open_conns: 10
  max_idle_conns: 10
  conn_max_life_time: "5m"
  retry: 10
  wait_duration: "10s"
  timeout: "30s"
  dbs:
    event_dbm:
      db_name: "event_db"
      account: "root" # should be replaced from environment variable
      password: "root" # should be replaced from environment variable
      ip: "127.0.0.1" # should be replaced from environment variable
      port: "3306" # should be replaced from environment variable
    event_dbs:
      db_name: "event_db"
      account: "root" # should be replaced from environment variable
      password: "root" # should be replaced from environment variable
      ip: "127.0.0.1" # should be replaced from environment variable
      port: "3306" # should be replaced from environment variable
    account_dbm:
      db_name: "account_db"
      account: "root" # should be replaced from environment variable
      password: "root" # should be replaced from environment variable
      ip: "127.0.0.1" # should be replaced from environment variable
      port: "3306" # should be replaced from environment variable
    account_dbs:
      db_name: "account_db"
      account: "root" # should be replaced from environment variable
      password: "root" # should be replaced from environment variable
      ip: "127.0.0.1" # should be replaced from environment variable
      port: "3306" # should be replaced from environment variable
# redis
redis:
  retry: 10             # ping retry times
  wait_duration: "1s"   # ping failure wait duration before next retry
  ping_timeout: "500ms" # ping timeout duration
  dbs:
    user: # user redis db
      read_timeout: "3s"
      write_timeout: "3s"
      max_retries: 3
      dial_timeout: "10s"
      pool_size: 50
      pool_timeout: "1800s"
      idle_timeout: "1800s"
      idle_check_frequency: "900s"
      host: "127.0.0.1:6379"
      db: 1